CREATE TABLE [dbo].[T_Country]
(
	[CountryID] INT IDENTITY NOT NULL,
	[Country] NVARCHAR(100)

	CONSTRAINT [PK_T_Country_CountryID] PRIMARY KEY CLUSTERED ([CountryID] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
