CREATE TABLE [dbo].[T_GroupTable]
(
	[GroupTableID] INT IDENTITY NOT NULL

	CONSTRAINT [PK_T_Group_GroupTableID] PRIMARY KEY CLUSTERED ([GroupTableID] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
)
