CREATE TABLE [dbo].[T_Group]
(
	[GroupID] INT IDENTITY NOT NULL, 
	[Name] NVARCHAR(50) NOT NULL,
	[NumberOf] INT NOT NULL,
	[GroupTable] INT NOT NULL,
	
	CONSTRAINT [PK_T_Group_GroupID] PRIMARY KEY CLUSTERED ([GroupID] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_T_Group_GroupTable] FOREIGN KEY ([GroupTable]) REFERENCES [dbo].[T_GroupTable]([GroupTableID])	
)

