CREATE TABLE [dbo].[T_ClubMember]
(
	[ClubMemberID] INT IDENTITY NOT NULL, 
	[Name] NVARCHAR(100) NOT NULL,
	[DateOfBirth] DATE NOT NULL,
	[ClubMemeberType] INT NOT NULL
	
	CONSTRAINT [PK_T_Person_ClubMemberID] PRIMARY KEY CLUSTERED ([ClubMemberID] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_T_ClubMember_ClubMemberType] FOREIGN KEY ([ClubMemeberType]) REFERENCES [dbo].[T_ClubMemeberType]([ClubMemeberTypeID])	
)