CREATE TABLE [dbo].[T_ClubMemeberType]
(
	[ClubMemeberTypeID] INT IDENTITY NOT NULL,
	[ClubMemeberType] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(50) NOT NULL

	CONSTRAINT [PK_T_ClubMemeberType_ClubMemeberTypeID] PRIMARY KEY CLUSTERED ([ClubMemeberTypeID] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
)
