CREATE TABLE [dbo].[T_League]
(
	[LeagueID] INT IDENTITY NOT NULL,
	[LeagueName] NVARCHAR(50) NOT NULL,
	[Country] INT NOT NULL

	CONSTRAINT [PK_T_Team_LeagueID] PRIMARY KEY CLUSTERED ([LeagueID] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_T_Country_Country] FOREIGN KEY ([Country]) REFERENCES [dbo].[T_Country]([CountryID])
)
