CREATE TABLE [dbo].[T_MatchEventType]
(
	[MatchEventTypeID] INT NOT NULL,

	CONSTRAINT [PK_T_MatchEvent_MatchEventTypeID] PRIMARY KEY CLUSTERED ([MatchEventTypeID] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
)
