CREATE TABLE [dbo].[T_Team]
(
	[TeamID] INT IDENTITY NOT NULL,
	[TeamName] NVARCHAR(100) NOT NULL,
	[League] INT NOT NULL

	CONSTRAINT [PK_T_Team_TeamID] PRIMARY KEY CLUSTERED ([TeamID] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_T_Leauge_Leauge] FOREIGN KEY ([League]) REFERENCES [dbo].[T_League]([LeagueID])
)
