CREATE TABLE [dbo].[T_TournamentType]
(
	[TournamentTypeID] INT NOT NULL,
	[TournamentType] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(100) NOT NULL

	CONSTRAINT [PK_T_TournamentType_TournamentTypeID] PRIMARY KEY CLUSTERED ([TournamentTypeID] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
